---
    - name: Obtener configuración actual de los Cipher Rules
      f5networks.f5_modules.bigip_command:
        commands:
          - list ltm cipher rule 
        provider: "{{ provider }}"
      register: Cipher_Rules
      delegate_to: localhost

    - name: Crear Cipher Rule STD
      shell: tmsh create ltm cipher rule {{ ciphers_rules }} cipher ECDHE:RSA:ECDHE_ECDSA:!SSLV3:!RC4:!EXP:!DES:!3DES:TLSV1_3
      when: "ciphers_rules not in Cipher_Rules.stdout[0]"
      notify: Save sys config

    - name: Obtener configuración actual de los Cipher Group
      f5networks.f5_modules.bigip_command:
        commands:
          - list ltm cipher group 
        provider: "{{ provider }}"
      register: Cipher_Group
      delegate_to: localhost

    
    - name: Crear Cipher Group STD
      shell: tmsh create ltm cipher group ciphers_group_STD allow add { {{ ciphers_rules }} }
      when: "'ciphers_rules_STD' not in Cipher_Rules.stdout[0] and 'ciphers_group_STD' not in Cipher_Group.stdout[0]"
      notify: Save sys config

    - name: Buscar Profile Client SSL
      f5networks.f5_modules.bigip_device_info:
        gather_subset:
          - client-ssl-profiles
        provider: "{{ provider }}"
      delegate_to: localhost
      register: Profile_Client_SSL

    - name: Crear Profile Client SSL
      f5networks.f5_modules.bigip_profile_client_ssl:
        name: "client_ssl_STD"
        state: present
        ciphers: none
        cipher_group: ciphers_group_STD
        options:
          - no-tlsv1.1
          - no-sslv3
          - no-tlsv1
          - no-ssl
        provider: "{{ provider }}"
      delegate_to: localhost
      when: "'ciphers_rules_STD' in Cipher_Rules.stdout[0] and 'ciphers_group_STD' in Cipher_Group.stdout[0] and 'client_ssl_STD' not in Profile_Client_SSL.ansible_facts.ansible_net_client_ssl_profiles | map(attribute='name') | list"
      notify: Save sys config

    - name: Buscar Profile Server SSL
      f5networks.f5_modules.bigip_device_info:
        gather_subset:
          - server-ssl-profiles
        provider: "{{ provider }}"
      delegate_to: localhost
      register: Profile_Server_SSL


    - name: Crear Profile Server SSL
      f5networks.f5_modules.bigip_profile_server_ssl:
        name: "server_ssl_STD"
        state: present
        ciphers: none
        cipher_group: ciphers_group_STD
        options:
          - no-tlsv1.1
          - no-sslv3
          - no-tlsv1
          - no-ssl
        provider: "{{ provider }}"
      delegate_to: localhost
      when: "'ciphers_rules_STD' in Cipher_Rules.stdout[0] and 'ciphers_group_STD'  in Cipher_Group.stdout[0] and 'server_ssl_STD' not in Profile_Server_SSL.ansible_facts.ansible_net_server_ssl_profiles | map(attribute='name') | list"
      notify: Save sys config